import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';
import RAPIER from 'https://cdn.jsdelivr.net/npm/@dimforge/rapier3d-compat@0.12.0/rapier.es.js';

await RAPIER.init();
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x90b8d0); scene.fog=new THREE.Fog(0x90b8d0,45,150);
const camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.05,300); camera.rotation.order='YXZ';
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; document.querySelector('#game').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xcceaff,0x43505c,2)); const sun=new THREE.DirectionalLight(0xfff3d0,3); sun.position.set(25,40,15); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048); scene.add(sun);
const world=new RAPIER.World({x:0,y:-9.81,z:0}); const dynamic=new Map(), bodies=new Map();
const COLORS={block:0x79899a,wood:0xb77b43,glass:0x52b9d5,metal:0x718096,seat:0xd25b4e,engine:0xe59c35,electric:0x71d47a,wheel:0x252a32,battery:0x7e63ce,button:0x4cc9aa,gate:0xa85be0};
const PARTS=[['block','Block'],['wood','Wood'],['metal','Metal'],['glass','Glass'],['seat','Seat'],['engine','Engine'],['electric','Motor'],['wheel','Wheel'],['battery','Battery'],['gate','AND Gate']];
let selected=0, mode='build', paused=false, pointerLocked=false, yaw=0,pitch=0, time=0, playerBody, playerGrounded=false, driver=null;
const keys=new Set(); const blocks=[]; const wires=[]; const ray=new THREE.Raycaster(); const clock=new THREE.Clock();
function mat(c,transparent=false){return new THREE.MeshStandardMaterial({color:c,roughness:.72,metalness:c===COLORS.metal?.7:.05,transparent,opacity:transparent?.55:1});}
function cubeMesh(type){let geo=new THREE.BoxGeometry(1,1,1); if(type==='wheel')geo=new THREE.CylinderGeometry(.48,.48,.28,20); if(type==='seat')geo=new THREE.BoxGeometry(.9,.65,.9); if(type==='engine')geo=new THREE.BoxGeometry(.8,.7,.8); return new THREE.Mesh(geo,mat(COLORS[type]??COLORS.block,type==='glass'));}
function key(x,y,z){return `${Math.round(x)},${Math.round(y)},${Math.round(z)}`}
function addBody(mesh,kinematic=false){const p=mesh.position; let desc=kinematic?RAPIER.RigidBodyDesc.kinematicPositionBased().setTranslation(p.x,p.y,p.z):RAPIER.RigidBodyDesc.dynamic().setTranslation(p.x,p.y,p.z).setLinearDamping(.3); const b=world.createRigidBody(desc); const c=RAPIER.ColliderDesc.cuboid(mesh.scale.x*.5,mesh.scale.y*.5,mesh.scale.z*.5).setFriction(.8); world.createCollider(c,b); bodies.set(mesh.uuid,b); return b}
function addPart(type,pos,rot=0,vehicleId=null){const k=key(pos.x,pos.y,pos.z); if(blocks.some(x=>x.key===k))return null; const mesh=cubeMesh(type); mesh.position.copy(pos); if(type==='wheel')mesh.rotation.z=Math.PI/2; mesh.rotation.y=rot; mesh.castShadow=mesh.receiveShadow=true; scene.add(mesh); const item={type,pos:pos.clone(),rot,key:k,mesh,vehicleId}; item.body=addBody(mesh); blocks.push(item); return item}
function removePart(item){scene.remove(item.mesh); const b=bodies.get(item.mesh.uuid);if(b)world.removeRigidBody(b); dynamic.delete(item.mesh.uuid); blocks.splice(blocks.indexOf(item),1)}
// floor
const floor=new THREE.Mesh(new THREE.BoxGeometry(160,1,160),mat(0x4b6657)); floor.position.y=-.5; floor.receiveShadow=true; scene.add(floor); const fd=RAPIER.RigidBodyDesc.fixed().setTranslation(0,-.5,0); const fb=world.createRigidBody(fd); world.createCollider(RAPIER.ColliderDesc.cuboid(80,.5,80),fb);
// starter creation
for(let x=-2;x<=2;x++)for(let z=-2;z<=2;z++)addPart('wood',new THREE.Vector3(x,.5,z)); addPart('seat',new THREE.Vector3(0,1.3,0)); addPart('engine',new THREE.Vector3(1,1.5,0)); addPart('wheel',new THREE.Vector3(-1.5,.5,-1.3));addPart('wheel',new THREE.Vector3(1.5,.5,-1.3));addPart('wheel',new THREE.Vector3(-1.5,.5,1.3));addPart('wheel',new THREE.Vector3(1.5,.5,1.3));
// player capsule
playerBody=world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(0,2,6).setEnabledRotations(false,true,false).setLinearDamping(.6)); world.createCollider(RAPIER.ColliderDesc.capsule(.65,.35),playerBody); camera.position.set(0,2,6);
function setupToolbar(){const bar=document.querySelector('#toolbar');PARTS.forEach((p,i)=>{const b=document.createElement('button');b.className='slot'+(i===0?' active':'');b.innerHTML=`<span class="swatch" style="background:#${COLORS[p[0]].toString(16)}"></span>${i+1} ${p[1]}`;b.onclick=()=>select(i);bar.append(b)})} function select(i){selected=i;document.querySelectorAll('.slot').forEach((b,n)=>b.classList.toggle('active',n===i))}setupToolbar();
function toast(s){const el=document.querySelector('#message');el.textContent=s;el.classList.add('toast');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('toast'),1800)}
function status(){document.querySelector('#mode').textContent=mode.toUpperCase()+' MODE';document.querySelector('#status').textContent=mode==='build'?`Selected: ${PARTS[selected][1]} · grid snap 1m · ${blocks.length} parts`:(driver?'Driving · engine power '+Math.round(driver.power):'Explore mode · E near a seat · Tab to build')}
function target(){ray.setFromCamera(new THREE.Vector2(0,0),camera);const hits=ray.intersectObjects(blocks.map(b=>b.mesh));return hits[0]}
function buildAction(place=true){const hit=target();if(!hit)return;if(!place){const item=blocks.find(b=>b.mesh===hit.object);if(item)removePart(item);status();return}const n=hit.face.normal.clone().transformDirection(hit.object.matrixWorld);const p=hit.object.position.clone().add(n).round();addPart(PARTS[selected][0],p,rotation);status()}
let rotation=0; function toggleMode(){mode=mode==='build'?'play':'build';if(mode==='build'&&driver){driver=null;toast('Exited vehicle')}status();}
function findSeat(){return blocks.filter(b=>b.type==='seat').sort((a,b)=>a.mesh.position.distanceTo(camera.position)-b.mesh.position.distanceTo(camera.position))[0]}
function enterSeat(){const s=findSeat();if(!s||s.mesh.position.distanceTo(camera.position)>3){toast('No seat nearby');return}driver=driver?null:{seat:s,power:0,steer:0};toast(driver?'Entered seat':'Exited seat');status()}
function save(){const data={blocks:blocks.map(b=>({type:b.type,x:b.mesh.position.x,y:b.mesh.position.y,z:b.mesh.position.z,rot:b.rot})),settings:{sensitivity:document.querySelector('#sensitivity').value,gravity:document.querySelector('#gravity').value}};localStorage.setItem('construct-lab-save',JSON.stringify(data));toast('Creation saved')}
function load(){const raw=localStorage.getItem('construct-lab-save');if(!raw){toast('No saved creation');return}blocks.slice().forEach(removePart);const d=JSON.parse(raw);d.blocks.forEach(b=>addPart(b.type,new THREE.Vector3(b.x,b.y,b.z),b.rot));toast('Creation loaded');status()}
function nearestEngine(){return blocks.find(b=>b.type==='engine'||b.type==='electric')}
function vehiclePhysics(dt){const e=nearestEngine();if(!driver||!e)return;const f=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0);const steer=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0);driver.power=THREE.MathUtils.lerp(driver.power,f*(e.type==='electric'?12:8),dt*5);driver.steer=steer;const pos=driver.seat.mesh.position;const dir=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw)); // apply force to all vehicle parts
blocks.forEach(b=>{if(['wood','metal','engine','electric','seat','wheel'].includes(b.type)){const rb=b.body;if(rb){rb.applyImpulse({x:dir.x*driver.power*dt,y:0,z:dir.z*driver.power*dt},true);if(b.type==='wheel')rb.applyTorqueImpulse({x:steer*driver.power*.2,y:0,z:0},true)}}}); camera.position.lerp(pos.clone().add(new THREE.Vector3(0,1.1,0)),.15)}
function playerPhysics(dt){if(driver)return;const dir=new THREE.Vector3((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),0,(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0));dir.applyAxisAngle(new THREE.Vector3(0,1,0),yaw);if(dir.lengthSq())dir.normalize().multiplyScalar(5);const v=playerBody.linvel();playerBody.setLinvel({x:dir.x,y:v.y,z:dir.z},true);if(keys.has('Space')&&Math.abs(v.y)<.08)playerBody.applyImpulse({x:0,y:5.5,z:0},true);const p=playerBody.translation();camera.position.set(p.x,p.y+.65,p.z);camera.rotation.set(pitch,yaw,0,'YXZ')}
function updateWires(){wires.splice(0).forEach(w=>scene.remove(w)); // visible connections between nearby power parts and gates
blocks.filter(b=>['battery','button','gate','engine','electric'].includes(b.type)).forEach(a=>blocks.filter(b=>b!==a&&b.type!=='block'&&a.mesh.position.distanceTo(b.mesh.position)<2.1).forEach(b=>{if(a.mesh.uuid>b.mesh.uuid)return;const g=new THREE.BufferGeometry().setFromPoints([a.mesh.position,b.mesh.position]);const line=new THREE.Line(g,new THREE.LineBasicMaterial({color:0xffd166}));scene.add(line);wires.push(line)}))}
renderer.domElement.addEventListener('click',()=>{if(!pointerLocked)renderer.domElement.requestPointerLock();else if(mode==='build')buildAction(true)});renderer.domElement.addEventListener('contextmenu',e=>{e.preventDefault();if(mode==='build')buildAction(false)});document.addEventListener('pointerlockchange',()=>pointerLocked=document.pointerLockElement===renderer.domElement);document.addEventListener('mousemove',e=>{if(!pointerLocked)return;yaw-=e.movementX*+document.querySelector('#sensitivity').value;pitch-=e.movementY*+document.querySelector('#sensitivity').value;pitch=Math.max(-1.5,Math.min(1.5,pitch))});document.addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Tab'){e.preventDefault();toggleMode()}if(e.code==='KeyR'&&mode==='build'){rotation=(rotation+Math.PI/2)%(Math.PI*2);toast('Rotation '+Math.round(rotation*180/Math.PI)+'°')}if(e.code==='KeyE'&&mode==='play')enterSeat();if(e.code==='KeyK')save();if(e.code==='KeyO')load();if(e.code==='KeyP'){paused=!paused;toast(paused?'Paused':'Resumed')}if(e.code==='F1')document.querySelector('#settings').classList.toggle('hidden');if(e.code.startsWith('Digit')){const n=+e.code.slice(5)-1;if(n<PARTS.length)select(n)}});document.addEventListener('keyup',e=>keys.delete(e.code));document.querySelector('#closeSettings').onclick=()=>document.querySelector('#settings').classList.add('hidden');document.querySelector('#gravity').oninput=e=>world.gravity={x:0,y:+e.target.value,z:0};
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);if(!paused){if(mode==='play'){playerPhysics(dt);vehiclePhysics(dt)}world.step();blocks.forEach(b=>{const t=b.body.translation();b.mesh.position.set(t.x,t.y,t.z);b.mesh.quaternion.set(b.body.rotation().x,b.body.rotation().y,b.body.rotation().z,b.body.rotation().w)});time+=dt;if(Math.floor(time*2)%2===0)updateWires()}status();renderer.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});status();loop();
