import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';
import RAPIER from 'https://cdn.jsdelivr.net/npm/@dimforge/rapier3d-compat@0.12.0/rapier.es.js';
await RAPIER.init();
const $=id=>document.getElementById(id),root=$('game-root'),toolbar=$('toolbar'),mode=$('mode-pill'),status=$('status-bar'),toastEl=$('toast'),settings=$('settings-panel');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc6d9);scene.fog=new THREE.Fog(0x9fc6d9,35,140);const camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.1,200);camera.rotation.order='YXZ';
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;root.appendChild(renderer.domElement);
const world=new RAPIER.World({x:0,y:-9.81,z:0});world.timestep=1/60;const ray=new THREE.Raycaster(),clock=new THREE.Clock(),keys=new Set(),parts=[],wires=new THREE.Group(),ghosts=new THREE.Group();scene.add(wires,ghosts);
const P={block:['Block',0x8ca4b7,[1,1,1]],wood:['Wood',0xb77d46,[1,1,1]],metal:['Metal',0x6c7e90,[1,1,1]],glass:['Glass',0x5ed1ef,[1,1,1]],seat:['Seat',0xd65c4c,[.9,.7,.9]],wheel:['Wheel',0x252b33,[.72,.72,.72],1],engine:['Engine',0xffae43,[1.1,.9,1.1],0,8],largeEngine:['Large Engine',0xf27625,[1.5,1,1.5],0,15],motor:['Motor',0x59d48b,[1,.8,1],0,10],battery:['Battery',0x7467d2,[1,1,1]],switch:['Switch',0x35cba5,[.7,.4,.7]],and:['AND Gate',0xc678e8,[.9,.9,.9]],or:['OR Gate',0xed9b4d,[.9,.9,.9]],not:['NOT Gate',0x55a6f2,[.9,.9,.9]],xor:['XOR Gate',0xf05b9a,[.9,.9,.9]]};
const order=Object.keys(P),geo=new Map(),mat=new Map(),s={mode:'build',selected:'block',rot:0,snap:1,yaw:0,pitch:0,sens:+$('sensitivity').value,locked:false,driver:null,paused:false,lastLogic:0,lastWire:0,ghost:null};
const notify=t=>{toastEl.textContent=t;toastEl.classList.add('visible');clearTimeout(notify.t);notify.t=setTimeout(()=>toastEl.classList.remove('visible'),1200)};
const label=t=>P[t][0];const key=v=>`${Math.round(v.x/s.snap)}:${Math.round(v.y/s.snap)}:${Math.round(v.z/s.snap)}`;
function geometry(t){if(!geo.has(t))geo.set(t,P[t][3]?new THREE.CylinderGeometry(.36,.36,.2,10):new THREE.BoxGeometry(...P[t][2]));return geo.get(t)}
function material(t,g=false){const k=t+g;if(!mat.has(k)){const p=P[t];mat.set(k,new THREE.MeshBasicMaterial({color:p[1],transparent:g||t==='glass',opacity:g?.3:t==='glass'?.5:1,depthWrite:!g}))}return mat.get(k)}
function mesh(t,g=false){const m=new THREE.Mesh(geometry(t),material(t,g));if(P[t][3])m.rotation.z=Math.PI/2;return m}
function add(t,pos,rot=0){const m=mesh(t);m.position.copy(pos);m.rotation.y=rot;const p={type:t,mesh:m,rot,signal:0,key:key(pos)};const d=RAPIER.RigidBodyDesc.dynamic().setTranslation(pos.x,pos.y,pos.z).setLinearDamping(.65).setAngularDamping(.8);p.body=world.createRigidBody(d);const a=P[t];world.createCollider(P[t][3]?RAPIER.ColliderDesc.cylinder(.1,.36):RAPIER.ColliderDesc.cuboid(a[2][0]/2,a[2][1]/2,a[2][2]/2),p.body);parts.push(p);scene.add(m);return p}
function remove(p){scene.remove(p.mesh);world.removeRigidBody(p.body);parts.splice(parts.indexOf(p),1)}
function updateStatus(){mode.textContent=s.mode.toUpperCase()+(s.driver?' · DRIVING':'')+' MODE';status.textContent=s.mode==='build'?`${label(s.selected)} · grid ${s.snap} · LMB place · RMB remove · R rotate`:s.driver?'W/S throttle · A/D steer · E exit':'WASD move · Space jump · E seat'}
function toolbarBuild(){toolbar.innerHTML='';order.forEach((t,i)=>{const b=document.createElement('button');b.className='part-slot';b.innerHTML=`<span class="part-color" style="background:#${P[t][1].toString(16).padStart(6,'0')}"></span><span>${i+1}. ${label(t)}</span>`;b.onclick=()=>select(t,i);toolbar.appendChild(b)});select('block',0)}
function select(t,i=order.indexOf(t)){s.selected=t;document.querySelectorAll('.part-slot').forEach((b,n)=>b.classList.toggle('active',n===i));updateStatus();ghost()}
function hit(){ray.setFromCamera(new THREE.Vector2(),camera);return ray.intersectObjects(parts.map(p=>p.mesh),false)[0]}
function placePos(){const h=hit();if(!h)return null;const n=h.face.normal.clone().transformDirection(h.object.matrixWorld);const q=h.point.clone().add(n.multiplyScalar(Math.max(...P[s.selected][2])*.5+.03));return new THREE.Vector3(Math.round(q.x/s.snap)*s.snap,Math.round(q.y/s.snap)*s.snap,Math.round(q.z/s.snap)*s.snap)}
function ghost(){ghosts.clear();s.ghost=s.mode==='build'?mesh(s.selected,true):null;if(s.ghost)ghosts.add(s.ghost)}
function ghostMove(){if(!s.ghost)return;const p=placePos();s.ghost.visible=!!p;if(p){s.ghost.position.copy(p);s.ghost.rotation.y=s.rot;s.ghost.material.color.set(parts.some(x=>x.key===key(p))?0xff5555:P[s.selected][1])}}
function place(){const p=placePos();if(p&&!parts.some(x=>x.key===key(p))){add(s.selected,p,s.rot);notify('Placed '+label(s.selected))}}
function removeTarget(){const h=hit();if(h){const p=parts.find(x=>x.mesh===h.object);if(p){remove(p);notify('Removed '+label(p.type))}}}
function toggle(){s.mode=s.mode==='build'?'play':'build';if(s.mode==='build'&&s.driver)exit();ghost();updateStatus();notify(s.mode+' mode')}
function nearestSeat(){const p=playerBody.translation();return parts.filter(x=>x.type==='seat').sort((a,b)=>Math.hypot(a.mesh.position.x-p.x,a.mesh.position.z-p.z)-Math.hypot(b.mesh.position.x-p.x,b.mesh.position.z-p.z))[0]}
function seat(){if(s.driver)return exit();const p=nearestSeat(),q=playerBody.translation();if(!p)return notify('No seat nearby');if(Math.hypot(p.mesh.position.x-q.x,p.mesh.position.z-q.z)>3.5)return notify('Seat too far');s.driver=p;updateStatus();notify('Entered seat')}
function exit(){if(!s.driver)return;const p=s.driver.mesh.position;playerBody.setTranslation({x:p.x,y:p.y+1.5,z:p.z+2},true);s.driver=null;updateStatus();notify('Exited seat')}
function logic(){if(clock.elapsedTime-s.lastLogic<.12)return;s.lastLogic=clock.elapsedTime;parts.forEach(p=>p.signal=0);parts.forEach(p=>{if(p.type==='battery')p.signal=1;if(p.type==='switch')p.signal=keys.has('KeyL')?1:0});const near=p=>parts.filter(x=>x!==p&&['battery','switch','and','or','not','xor','engine','largeEngine','motor'].includes(x.type)&&x.mesh.position.distanceTo(p.mesh.position)<3.2);for(let n=0;n<3;n++)parts.filter(p=>['and','or','not','xor'].includes(p.type)).forEach(g=>{const a=near(g).map(x=>!!x.signal),op=g.type;g.signal=op==='and'?a.length>1&&a.every(Boolean):op==='or'?a.some(Boolean):op==='not'?a.length>0&&!a[0]:a.filter(Boolean).length===1});parts.filter(p=>['engine','largeEngine','motor'].includes(p.type)).forEach(p=>p.signal=near(p).some(x=>x.signal)?1:0)}
function drawWires(){if(clock.elapsedTime-s.lastWire<.2)return;s.lastWire=clock.elapsedTime;wires.clear();const n=parts.filter(p=>['battery','switch','and','or','not','xor','engine','largeEngine','motor'].includes(p.type)),v=[];for(let i=0;i<n.length;i++)for(let j=i+1;j<n.length;j++)if(n[i].mesh.position.distanceTo(n[j].mesh.position)<3.2)v.push(n[i].mesh.position,n[j].mesh.position);if(!v.length)return;const a=[];for(let i=0;i<v.length;i+=2)a.push(v[i].x,v[i].y,v[i].z,v[i+1].x,v[i+1].y,v[i+1].z);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(a,3));wires.add(new THREE.LineSegments(g,new THREE.LineBasicMaterial({color:0xffd45f})))}
function drive(dt){if(!s.driver)return;const v=parts,w=v.filter(p=>p.type==='wheel'),m=v.filter(p=>['engine','largeEngine','motor'].includes(p.type)),th=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),st=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),f=new THREE.Vector3(Math.sin(s.yaw),0,Math.cos(s.yaw)),power=m.reduce((a,p)=>a+(P[p.type][4]||0),0),imp=th*power*dt*.08;w.forEach(x=>{x.body.applyImpulse({x:f.x*imp,y:0,z:f.z*imp},true);x.body.applyTorqueImpulse({x:0,y:st*power*dt*.01,z:0},true)});const p=s.driver.mesh.position;camera.position.lerp(new THREE.Vector3(p.x,p.y+1.2,p.z+.6),.2);camera.rotation.set(s.pitch,s.yaw,0,'YXZ')}
function player(){if(s.driver)return;const i=new THREE.Vector3((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),0,(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0));if(i.lengthSq())i.applyAxisAngle(new THREE.Vector3(0,1,0),s.yaw).normalize();const v=playerBody.linvel();playerBody.setLinvel({x:i.x*5.8,y:v.y,z:i.z*5.8},true);if(keys.has('Space')&&playerBody.translation().y<1.8&&Math.abs(v.y)<.3)playerBody.applyImpulse({x:0,y:6,z:0},true);const p=playerBody.translation();camera.position.set(p.x,p.y+1.2,p.z);camera.rotation.set(s.pitch,s.yaw,0,'YXZ')}
function save(){localStorage.setItem('construct-lab-save-v5',JSON.stringify(parts.map(p=>({type:p.type,x:p.mesh.position.x,y:p.mesh.position.y,z:p.mesh.position.z,rotation:p.rot}))));notify('Build saved')}
function load(){const raw=localStorage.getItem('construct-lab-save-v5');if(!raw)return notify('No save found');parts.slice().forEach(remove);JSON.parse(raw).forEach(p=>add(p.type,new THREE.Vector3(p.x,p.y,p.z),p.rotation||0));notify('Build loaded')}
function down(e){keys.add(e.code);if(e.code==='Tab'){e.preventDefault();toggle()}if(e.code==='KeyE'&&s.mode==='play')seat();if(e.code==='KeyK')save();if(e.code==='KeyO')load();if(e.code==='KeyP'){s.paused=!s.paused;notify(s.paused?'Paused':'Resumed')}if(e.code==='KeyR'&&s.mode==='build'){s.rot+=Math.PI/2;notify('Rotated 90°')}if(e.code==='F1')settings.classList.toggle('hidden');if(e.code.startsWith('Digit')){const i=+e.code.slice(5)-1;if(order[i])select(order[i],i)}}
const playerBody=world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(0,2,8).setLinearDamping(.4).setEnabledRotations(false,true,false));world.createCollider(RAPIER.ColliderDesc.capsule(.45,.55),playerBody);
document.addEventListener('keydown',down);document.addEventListener('keyup',e=>keys.delete(e.code));document.addEventListener('mousemove',e=>{if(s.locked){s.yaw-=e.movementX*s.sens;s.pitch=THREE.MathUtils.clamp(s.pitch-e.movementY*s.sens,-1.45,1.45)}});renderer.domElement.onmousedown=e=>{if(!s.locked){renderer.domElement.requestPointerLock();return}if(s.mode==='build')e.button===0?place():e.button===2?removeTarget():0};document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('pointerlockchange',()=>s.locked=document.pointerLockElement===renderer.domElement);$('sensitivity').oninput=e=>s.sens=+e.target.value;$('gravity').oninput=e=>world.gravity={x:0,y:+e.target.value,z:0};snapInput.oninput=e=>{s.snap=+e.target.value;updateStatus()};$('close-settings').onclick=()=>settings.classList.add('hidden');addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
scene.add(new THREE.HemisphereLight(0xd9f1ff,0x27333c,1.2));const sun=new THREE.DirectionalLight(0xffe8b4,1.3);sun.position.set(25,35,15);scene.add(sun);const ground=new THREE.Mesh(new THREE.BoxGeometry(140,1,140),new THREE.MeshBasicMaterial({color:0x4c6654}));ground.position.y=-.5;scene.add(ground);const gb=world.createRigidBody(RAPIER.RigidBodyDesc.fixed().setTranslation(0,-.5,0));world.createCollider(RAPIER.ColliderDesc.cuboid(70,.5,70),gb);add('wood',new THREE.Vector3(0,1,1));add('wood',new THREE.Vector3(1,1,1));add('seat',new THREE.Vector3(0,2,1));add('engine',new THREE.Vector3(0,1.2,-1));add('battery',new THREE.Vector3(0,2.1,-2));for(const p of[[-1.5,.5,-.7],[1.5,.5,-.7],[-1.5,.5,1.8],[1.5,.5,1.8]])add('wheel',new THREE.Vector3(...p));toolbarBuild();ghost();updateStatus();
function frame(){requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.05);if(s.mode==='build')ghostMove();if(!s.paused){if(s.mode==='play'){player();drive(dt)}logic();world.step();parts.forEach(p=>{const t=p.body.translation(),q=p.body.rotation();p.mesh.position.set(t.x,t.y,t.z);p.mesh.quaternion.set(q.x,q.y,q.z,q.w)});drawWires()}renderer.render(scene,camera)}frame();notify('Optimized prototype ready');window.__constructLab={save,load,parts,state:s};